FROM golang:1.19.5-buster
LABEL owner="My app"

RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates  \
        netbase \
        libssl-dev \
        && apt-get autoremove -y && apt-get autoclean -y

RUN go install github.com/cosmtrek/air@v1

WORKDIR /go/src/kafkacheck

CMD ["air", "-c", "/etc/.air.toml"]